extern const GeoLayout course0_area_1_geo[];
extern const GeoLayout course0_area_1[];
extern const Collision course0_area_1_collision[];
extern const MacroObject course0_area_1_macro_objs[];
extern Vtx course0_dl_gfx_dummy35_mesh_mesh_layer_1_vtx_0[959];
extern Gfx course0_dl_gfx_dummy35_mesh_mesh_layer_1_tri_0[];
extern Vtx course0_dl_gfx_dummy35_mesh_mesh_layer_1_vtx_1[28];
extern Gfx course0_dl_gfx_dummy35_mesh_mesh_layer_1_tri_1[];
extern Gfx mat_course0_dl_f3dlite_material_003[];
extern Gfx mat_revert_course0_dl_f3dlite_material_003[];
extern Gfx mat_course0_dl_f3dlite_material_001[];
extern Gfx mat_revert_course0_dl_f3dlite_material_001[];
extern Gfx course0_dl_gfx_dummy35_mesh_mesh_layer_1[];
extern Gfx course0_dl_material_revert_render_settings[];
