extern void scroll_castle_grounds_dl_castle_grounds_seg7_dl_0700A290_mesh_001_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds();
