extern void scroll_castle_grounds_dl_mesh1_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Water_Box_Mesh_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds_dl_Water_Box_Mesh_001_mesh_layer_5_vtx_0();
extern void scroll_castle_grounds();
