#ifndef GROUP0_H
#define GROUP0_H

#include "types.h"

// bubble
extern const GeoLayout bubble_geo[];
extern const GeoLayout purple_marble_geo[];
extern const Gfx bubble_seg4_dl_0401DD60[];
extern const Gfx bubble_seg4_dl_0401DDE0[];

// burn_smoke
extern const GeoLayout burn_smoke_geo[];
extern const Gfx burn_smoke_seg4_sub_dl_begin[];
extern const Gfx burn_smoke_seg4_sub_dl_model[];
extern const Gfx burn_smoke_seg4_sub_dl_end[];
extern const Gfx burn_smoke_seg4_dl[];


// mario
extern const GeoLayout mario_geo_face_and_wings[];
extern const GeoLayout mario_geo_left_hand[];
extern const GeoLayout mario_geo_right_hand[];
extern const GeoLayout mario_geo_body[];
extern const GeoLayout mario_geo_medium_poly_left_hand[];
extern const GeoLayout mario_geo_medium_poly_right_hand[];
extern const GeoLayout mario_geo_medium_poly_body[];
extern const GeoLayout mario_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_geo_low_poly_left_hand[];
extern const GeoLayout mario_geo_low_poly_right_hand[];
extern const GeoLayout mario_geo_low_poly_body[];
extern const GeoLayout mario_vanish_geo_face_and_wings[];
extern const GeoLayout mario_vanish_geo_left_hand[];
extern const GeoLayout mario_vanish_geo_right_hand[];
extern const GeoLayout mario_vanish_geo_body[];
extern const GeoLayout mario_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout mario_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout mario_vanish_geo_medium_poly_body[];
extern const GeoLayout mario_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_vanish_geo_low_poly_left_hand[];
extern const GeoLayout mario_vanish_geo_low_poly_right_hand[];
extern const GeoLayout mario_vanish_geo_low_poly_body[];
extern const GeoLayout mario_metal_geo_face_and_wings[];
extern const GeoLayout mario_metal_geo_left_hand[];
extern const GeoLayout mario_metal_geo_right_hand[];
extern const GeoLayout mario_metal_geo_body[];
extern const GeoLayout mario_metal_geo_medium_poly_left_hand[];
extern const GeoLayout mario_metal_geo_medium_poly_right_hand[];
extern const GeoLayout mario_metal_geo_medium_poly_body[];
extern const GeoLayout mario_metal_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_metal_geo_low_poly_left_hand[];
extern const GeoLayout mario_metal_geo_low_poly_right_hand[];
extern const GeoLayout mario_metal_geo_low_poly_body[];
extern const GeoLayout mario_metal_vanish_geo_face_and_wings[];
extern const GeoLayout mario_metal_vanish_geo_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_body[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_medium_poly_body[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_left_hand[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_right_hand[];
extern const GeoLayout mario_metal_vanish_geo_low_poly_body[];
extern const GeoLayout mario_geo_load_body[];
extern const GeoLayout mario_geo_load_medium_poly_body[];
extern const GeoLayout mario_geo_load_low_poly_body[];
extern const GeoLayout mario_geo_render_body[];
extern const GeoLayout mario_geo[];
extern const Gfx mario_butt_dl[];
extern const Gfx mario_butt[];
extern const Gfx mario_metal_butt[];
extern const Gfx mario_left_arm_shared_dl[];
extern const Gfx mario_left_arm[];
extern const Gfx mario_left_forearm_shared_dl[];
extern const Gfx mario_left_hand_closed_shared_dl[];
extern const Gfx mario_left_hand_closed[];
extern const Gfx mario_right_arm_shared_dl[];
extern const Gfx mario_right_arm[];
extern const Gfx mario_right_forearm_shared_dl[];
extern const Gfx mario_right_hand_closed_dl[];
extern const Gfx mario_right_hand_closed[];
extern const Gfx mario_metal_right_hand_closed[];
extern const Gfx mario_left_thigh_dl[];
extern const Gfx mario_left_thigh[];
extern const Gfx mario_metal_left_thigh[];
extern const Gfx mario_left_leg_shared_dl[];
extern const Gfx mario_left_foot_shared_dl[];
extern const Gfx mario_left_foot[];
extern const Gfx mario_right_thigh_shared_dl[];
extern const Gfx mario_right_thigh[];
extern const Gfx mario_right_leg_shared_dl[];
extern const Gfx mario_right_foot_dl[];
extern const Gfx mario_right_foot[];
extern const Gfx mario_metal_right_foot[];
extern const Gfx mario_yellow_button_dl[];
extern const Gfx mario_pants_overalls_shared_dl[];
extern const Gfx mario_tshirt_shared_dl[];
extern const Gfx mario_torso_dl[];
extern const Gfx mario_torso[];
extern const Gfx mario_metal_torso_shared_dl[];
extern const Gfx mario_m_logo_dl[];
extern const Gfx mario_eyes_cap_on_dl[];
extern const Gfx mario_hair_sideburn_cap_on_dl[];
extern const Gfx mario_mustache_cap_on_dl[];
extern const Gfx mario_face_part_cap_on_dl[];
extern const Gfx mario_face_cap_dl[];
extern const Gfx mario_face_back_hair_cap_on_dl[];
extern const Gfx mario_face_cap_on_dl[];
extern const Gfx mario_cap_on_eyes_front[];
extern const Gfx mario_cap_on_eyes_half_closed[];
extern const Gfx mario_cap_on_eyes_closed[];
extern const Gfx mario_cap_on_eyes_right[];
extern const Gfx mario_cap_on_eyes_left[];
extern const Gfx mario_cap_on_eyes_up[];
extern const Gfx mario_cap_on_eyes_down[];
extern const Gfx mario_cap_on_eyes_dead[];
extern const Gfx mario_metal_cap_on_shared_dl[];
extern const Gfx mario_eyes_cap_off_dl[];
extern const Gfx mario_mustache_cap_off_dl[];
extern const Gfx mario_hair_sideburn_cap_off_dl[];
extern const Gfx mario_face_part_cap_off_dl[];
extern const Gfx mario_face_hair_cap_off_dl[];
extern const Gfx mario_face_cap_off_dl[];
extern const Gfx mario_cap_off_eyes_front[];
extern const Gfx mario_cap_off_eyes_half_closed[];
extern const Gfx mario_cap_off_eyes_closed[];
extern const Gfx mario_cap_off_eyes_right[];
extern const Gfx mario_cap_off_eyes_left[];
extern const Gfx mario_cap_off_eyes_up[];
extern const Gfx mario_cap_off_eyes_down[];
extern const Gfx mario_cap_off_eyes_dead[];
extern const Gfx mario_metal_cap_off_shared_dl[];
extern const Gfx mario_medium_poly_butt_dl[];
extern const Gfx mario_medium_poly_butt[];
extern const Gfx mario_metal_medium_poly_butt[];
extern const Gfx mario_medium_poly_left_arm_shared_dl[];
extern const Gfx mario_medium_poly_left_arm[];
extern const Gfx mario_medium_poly_left_forearm_shared_dl[];
extern const Gfx mario_medium_poly_left_hand_closed_shared_dl[];
extern const Gfx mario_medium_poly_left_hand_closed[];
extern const Gfx mario_medium_poly_right_arm_shared_dl[];
extern const Gfx mario_medium_poly_right_arm[];
extern const Gfx mario_medium_poly_right_forearm_shared_dl[];
extern const Gfx mario_medium_poly_right_hand_closed_dl[];
extern const Gfx mario_medium_poly_right_hand_closed[];
extern const Gfx mario_metal_medium_poly_right_hand_closed[];
extern const Gfx mario_medium_poly_left_thigh_dl[];
extern const Gfx mario_medium_poly_left_thigh[];
extern const Gfx mario_metal_medium_poly_left_thigh[];
extern const Gfx mario_medium_poly_left_leg_shared_dl[];
extern const Gfx mario_medium_poly_left_foot_shared_dl[];
extern const Gfx mario_medium_poly_left_foot[];
extern const Gfx mario_medium_poly_right_thigh_shared_dl[];
extern const Gfx mario_medium_poly_right_thigh[];
extern const Gfx mario_medium_poly_right_leg_shared_dl[];
extern const Gfx mario_medium_poly_right_foot_dl[];
extern const Gfx mario_medium_poly_right_foot[];
extern const Gfx mario_metal_medium_poly_right_foot[];
extern const Gfx mario_medium_poly_yellow_button_dl[];
extern const Gfx mario_medium_poly_pants_overalls_shared_dl[];
extern const Gfx mario_medium_poly_tshirt_shared_dl[];
extern const Gfx mario_medium_poly_torso_dl[];
extern const Gfx mario_medium_poly_torso[];
extern const Gfx mario_metal_medium_poly_torso[];
extern const Gfx mario_low_poly_butt_dl[];
extern const Gfx mario_low_poly_butt[];
extern const Gfx mario_metal_low_poly_butt[];
extern const Gfx mario_low_poly_left_arm_shared_dl[];
extern const Gfx mario_low_poly_left_arm[];
extern const Gfx mario_low_poly_left_forearm_shared_dl[];
extern const Gfx mario_low_poly_left_hand_closed_shared_dl[];
extern const Gfx mario_low_poly_left_hand_closed[];
extern const Gfx mario_low_poly_right_arm_shared_dl[];
extern const Gfx mario_low_poly_right_arm[];
extern const Gfx mario_low_poly_right_forearm_shared_dl[];
extern const Gfx mario_low_poly_right_hand_closed_dl[];
extern const Gfx mario_low_poly_right_hand_closed[];
extern const Gfx mario_metal_low_poly_right_hand_closed[];
extern const Gfx mario_low_poly_left_thigh_dl[];
extern const Gfx mario_low_poly_left_thigh[];
extern const Gfx mario_metal_low_poly_left_thigh[];
extern const Gfx mario_low_poly_left_leg_shared_dl[];
extern const Gfx mario_low_poly_left_foot_shared_dl[];
extern const Gfx mario_low_poly_left_foot[];
extern const Gfx mario_low_poly_right_thigh_shared_dl[];
extern const Gfx mario_low_poly_right_thigh[];
extern const Gfx mario_low_poly_right_leg_shared_dl[];
extern const Gfx mario_low_poly_right_foot_dl[];
extern const Gfx mario_low_poly_right_foot[];
extern const Gfx mario_metal_low_poly_right_foot[];
extern const Gfx mario_low_poly_yellow_button_dl[];
extern const Gfx mario_low_poly_pants_overalls_shared_dl[];
extern const Gfx mario_low_poly_tshirt_shared_dl[];
extern const Gfx mario_low_poly_torso_dl[];
extern const Gfx mario_low_poly_torso[];
extern const Gfx mario_metal_low_poly_torso[];
extern const Gfx mario_low_poly_mario_m_logo_dl[];
extern const Gfx mario_low_poly_eyes_cap_on_dl[];
extern const Gfx mario_low_poly_mustache_cap_on_dl[];
extern const Gfx mario_low_poly_face_part_cap_on_dl[];
extern const Gfx mario_low_poly_face_cap_dl[];
extern const Gfx mario_low_poly_face_back_hair_cap_on_dl[];
extern const Gfx mario_low_poly_face_cap_on_dl[];
extern const Gfx mario_low_poly_cap_on_eyes_front[];
extern const Gfx mario_low_poly_cap_on_eyes_half_closed[];
extern const Gfx mario_low_poly_cap_on_eyes_closed[];
extern const Gfx mario_low_poly_cap_on_eyes_right[];
extern const Gfx mario_low_poly_cap_on_eyes_left[];
extern const Gfx mario_low_poly_cap_on_eyes_up[];
extern const Gfx mario_low_poly_cap_on_eyes_down[];
extern const Gfx mario_low_poly_cap_on_eyes_dead[];
extern const Gfx mario_metal_low_poly_cap_on[];
extern const Gfx mario_low_poly_mario_eyes_cap_off_dl[];
extern const Gfx mario_low_poly_mustache_cap_off_dl[];
extern const Gfx mario_low_poly_face_part_cap_off_dl[];
extern const Gfx mario_low_poly_face_hair_cap_off_dl[];
extern const Gfx mario_low_poly_face_cap_off_dl[];
extern const Gfx mario_low_poly_cap_off_eyes_front[];
extern const Gfx mario_low_poly_cap_off_eyes_half_closed[];
extern const Gfx mario_low_poly_cap_off_eyes_closed[];
extern const Gfx mario_low_poly_cap_off_eyes_right[];
extern const Gfx mario_low_poly_cap_off_eyes_left[];
extern const Gfx mario_low_poly_cap_off_eyes_up[];
extern const Gfx mario_low_poly_cap_off_eyes_down[];
extern const Gfx mario_low_poly_cap_off_eyes_dead[];
extern const Gfx mario_metal_low_poly_cap_off[];
extern const Gfx mario_left_hand_open_shared_dl[];
extern const Gfx mario_left_hand_open[];
extern const Gfx mario_right_hand_open_dl[];
extern const Gfx mario_right_hand_open[];
extern const Gfx mario_metal_right_hand_open[];
extern const Gfx mario_right_hand_cap_m_logo_dl[];
extern const Gfx mario_right_hand_cap_top_dl[];
extern const Gfx mario_right_hand_cap_hand_position_dl[];
extern const Gfx mario_right_hand_cap_bottom_dl[];
extern const Gfx mario_right_hand_cap_dl[];
extern const Gfx mario_right_hand_cap_wings_half_1_dl[];
extern const Gfx mario_right_hand_cap_wings_half_2_dl[];
extern const Gfx mario_right_hand_cap_wings_initial_dl[];
extern const Gfx mario_right_hand_cap_wings_end_dl[];
extern const Gfx mario_right_hand_cap[];
extern const Gfx mario_right_hand_cap_wings[];
extern const Gfx mario_metal_right_hand_cap_shared_dl[];
extern const Gfx mario_metal_right_hand_cap_shared_dl_wings[];
extern const Gfx mario_right_hand_peace_shared_dl[];
extern const Gfx mario_right_hand_peace[];
extern const Gfx mario_cap_unused_m_logo_dl[];
extern const Gfx mario_cap_unused_base_top_dl[];
extern const Gfx mario_cap_unused_base_bottom_dl[];
extern const Gfx mario_cap_unused_base_dl[];
extern const Gfx mario_wings_half_1_unused_dl[];
extern const Gfx mario_wings_half_2_unused_dl[];
extern const Gfx mario_cap_wings_unused_initial_dl[];
extern const Gfx mario_cap_wings_unused_end_dl[];
extern const Gfx mario_cap_unused_dl[];
extern const Gfx mario_metal_cap_unused_dl[];
extern const Gfx mario_cap_wings_unused[];
extern const Gfx mario_metal_cap_wings_unused[];
extern const Gfx mario_wings_half_1_dl[];
extern const Gfx mario_wings_half_2_dl[];
extern const Gfx mario_cap_wings[];
extern const Gfx mario_cap_wings_transparent[];
extern const Gfx mario_metal_cap_wings[];
extern const Gfx mario_metal_cap_wings_transparent[];

// sparkle
extern const GeoLayout sparkles_geo[];
extern const Gfx sparkles_seg4_dl_0402A490[];
extern const Gfx sparkles_seg4_dl_0402A4F8[];
extern const Gfx sparkles_seg4_dl_0402A510[];
extern const Gfx sparkles_seg4_dl_0402A528[];
extern const Gfx sparkles_seg4_dl_0402A540[];
extern const Gfx sparkles_seg4_dl_0402A558[];
extern const Gfx sparkles_seg4_dl_0402A570[];

// sparkle_animation
extern const GeoLayout sparkles_animation_geo[];
extern const Gfx sparkles_animation_seg4_dl_04035288[];
extern const Gfx sparkles_animation_seg4_dl_04035300[];
extern const Gfx sparkles_animation_seg4_dl_04035318[];
extern const Gfx sparkles_animation_seg4_dl_04035330[];
extern const Gfx sparkles_animation_seg4_dl_04035348[];
extern const Gfx sparkles_animation_seg4_dl_04035360[];

// small water splash
extern const GeoLayout small_water_splash_geo[];
extern const Gfx small_water_splash_seg4_dl_0[];
extern const Gfx small_water_splash_seg4_dl_1[];
extern const Gfx small_water_splash_seg4_dl_2[];
extern const Gfx small_water_splash_seg4_dl_3[];
extern const Gfx small_water_splash_seg4_dl_4[];
extern const Gfx small_water_splash_seg4_dl_5[];

// walk_smoke
extern const GeoLayout smoke_geo[];
extern const Gfx smoke_seg4_dl_040216A0[];
extern const Gfx smoke_seg4_dl_04021718[];
extern const Gfx smoke_seg4_dl_04021730[];
extern const Gfx smoke_seg4_dl_04021748[];
extern const Gfx smoke_seg4_dl_04021760[];
extern const Gfx smoke_seg4_dl_04021778[];
extern const Gfx smoke_seg4_dl_04021790[];
extern const Gfx smoke_seg4_dl_040217A8[];

// water_splash
extern const GeoLayout water_splash_geo[];
extern const Gfx water_splash_seg4_dl_040325C8[];
extern const Gfx water_splash_seg4_dl_04032640[];
extern const Gfx water_splash_seg4_dl_04032658[];
extern const Gfx water_splash_seg4_dl_04032670[];
extern const Gfx water_splash_seg4_dl_04032688[];
extern const Gfx water_splash_seg4_dl_040326A0[];
extern const Gfx water_splash_seg4_dl_040326B8[];
extern const Gfx water_splash_seg4_dl_040326D0[];
extern const Gfx water_splash_seg4_dl_040326E8[];

// water_waves
extern const GeoLayout idle_water_wave_geo[];
extern const GeoLayout wave_trail_geo[];
extern const Gfx water_wave_seg4_dl_04027358[];
extern const Gfx water_wave_seg4_dl_040273A0[];
extern const Gfx water_wave_seg4_dl_040273D8[];
extern const Gfx water_wave_seg4_dl_040273F0[];
extern const Gfx water_wave_seg4_dl_04027408[];
extern const Gfx water_wave_seg4_dl_04027420[];
extern const Gfx water_wave_seg4_dl_04027438[];

// white_particle_small
extern const Gfx white_particle_small_dl_begin[];
extern const Gfx white_particle_small_dl_end[];
extern const Gfx white_particle_small_dl[];
extern const Gfx white_particle_small_unused_dl[];

// luigi
extern const GeoLayout luigi_geo_face_and_wings[];
extern const GeoLayout luigi_geo_left_hand[];
extern const GeoLayout luigi_geo_right_hand[];
extern const GeoLayout luigi_geo_body[];
extern const GeoLayout luigi_geo_medium_poly_left_hand[];
extern const GeoLayout luigi_geo_medium_poly_right_hand[];
extern const GeoLayout luigi_geo_medium_poly_body[];
extern const GeoLayout luigi_geo_low_poly_face_and_wings[];
extern const GeoLayout luigi_geo_low_poly_left_hand[];
extern const GeoLayout luigi_geo_low_poly_right_hand[];
extern const GeoLayout luigi_geo_low_poly_body[];
extern const GeoLayout luigi_vanish_geo_face_and_wings[];
extern const GeoLayout luigi_vanish_geo_left_hand[];
extern const GeoLayout luigi_vanish_geo_right_hand[];
extern const GeoLayout luigi_vanish_geo_body[];
extern const GeoLayout luigi_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout luigi_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout luigi_vanish_geo_medium_poly_body[];
extern const GeoLayout luigi_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout luigi_vanish_geo_low_poly_left_hand[];
extern const GeoLayout luigi_vanish_geo_low_poly_right_hand[];
extern const GeoLayout luigi_vanish_geo_low_poly_body[];
extern const GeoLayout luigi_metal_geo_face_and_wings[];
extern const GeoLayout luigi_metal_geo_left_hand[];
extern const GeoLayout luigi_metal_geo_right_hand[];
extern const GeoLayout luigi_metal_geo_body[];
extern const GeoLayout luigi_metal_geo_medium_poly_left_hand[];
extern const GeoLayout luigi_metal_geo_medium_poly_right_hand[];
extern const GeoLayout luigi_metal_geo_medium_poly_body[];
extern const GeoLayout luigi_metal_geo_low_poly_face_and_wings[];
extern const GeoLayout luigi_metal_geo_low_poly_left_hand[];
extern const GeoLayout luigi_metal_geo_low_poly_right_hand[];
extern const GeoLayout luigi_metal_geo_low_poly_body[];
extern const GeoLayout luigi_metal_vanish_geo_face_and_wings[];
extern const GeoLayout luigi_metal_vanish_geo_left_hand[];
extern const GeoLayout luigi_metal_vanish_geo_right_hand[];
extern const GeoLayout luigi_metal_vanish_geo_body[];
extern const GeoLayout luigi_metal_vanish_geo_medium_poly_left_hand[];
extern const GeoLayout luigi_metal_vanish_geo_medium_poly_right_hand[];
extern const GeoLayout luigi_metal_vanish_geo_medium_poly_body[];
extern const GeoLayout luigi_metal_vanish_geo_low_poly_face_and_wings[];
extern const GeoLayout luigi_metal_vanish_geo_low_poly_left_hand[];
extern const GeoLayout luigi_metal_vanish_geo_low_poly_right_hand[];
extern const GeoLayout luigi_metal_vanish_geo_low_poly_body[];
extern const GeoLayout luigi_geo_load_body[];
extern const GeoLayout luigi_geo_load_medium_poly_body[];
extern const GeoLayout luigi_geo_load_low_poly_body[];
extern const GeoLayout luigi_geo_render_body[];
extern const GeoLayout luigi_geo[];
extern const Gfx luigi_head_NO_CAP_skinned_001_mesh[];
extern const Gfx luigi_head_NO_CAP_skinned_002_mesh[];
extern const Gfx luigi_head_NO_CAP_skinned_003_mesh[];
extern const Gfx luigi_head_NO_CAP_skinned_004_mesh[];
extern Gfx luigi_head_skinned_001_mesh[];
extern Gfx luigi_head_skinned_002_mesh[];
extern Gfx luigi_head_skinned_003_mesh[];
extern Gfx luigi_head_skinned_004_mesh[];
extern Gfx luigi_head_skinned_005_mesh[];
extern Gfx luigi_head_skinned_006_mesh[];
extern const Gfx luigi_butt_dl[];
extern const Gfx luigi_butt[];
extern const Gfx luigi_metal_butt[];
extern const Gfx luigi_left_arm_shared_dl[];
extern const Gfx luigi_left_arm[];
extern const Gfx luigi_left_forearm_shared_dl[];
extern const Gfx luigi_left_hand_closed_shared_dl[];
extern const Gfx luigi_left_hand_closed[];
extern const Gfx luigi_right_arm_shared_dl[];
extern const Gfx luigi_right_arm[];
extern const Gfx luigi_right_forearm_shared_dl[];
extern const Gfx luigi_right_hand_closed_dl[];
extern const Gfx luigi_right_hand_closed[];
extern const Gfx luigi_metal_right_hand_closed[];
extern const Gfx luigi_left_thigh_dl[];
extern const Gfx luigi_left_thigh[];
extern const Gfx luigi_metal_left_thigh[];
extern const Gfx luigi_left_leg_shared_dl[];
extern const Gfx luigi_left_foot_shared_dl[];
extern const Gfx luigi_left_foot[];
extern const Gfx luigi_right_thigh_shared_dl[];
extern const Gfx luigi_right_thigh[];
extern const Gfx luigi_right_leg_shared_dl[];
extern const Gfx luigi_right_foot_dl[];
extern const Gfx luigi_right_foot[];
extern const Gfx luigi_metal_right_foot[];
extern const Gfx luigi_yellow_button_dl[];
extern const Gfx luigi_pants_overalls_shared_dl[];
extern const Gfx luigi_tshirt_shared_dl[];
extern const Gfx luigi_torso_dl[];
extern const Gfx luigi_torso[];
extern const Gfx luigi_metal_torso_shared_dl[];
extern const Gfx luigi_m_logo_dl[];
extern const Gfx luigi_eyes_cap_on_dl[];
extern const Gfx luigi_hair_sideburn_cap_on_dl[];
extern const Gfx luigi_mustache_cap_on_dl[];
extern const Gfx luigi_face_part_cap_on_dl[];
extern const Gfx luigi_face_cap_dl[];
extern const Gfx luigi_face_back_hair_cap_on_dl[];
extern const Gfx luigi_face_cap_on_dl[];
extern const Gfx luigi_cap_on_eyes_front[];
extern const Gfx luigi_cap_on_eyes_half_closed[];
extern const Gfx luigi_cap_on_eyes_closed[];
extern const Gfx luigi_cap_on_eyes_right[];
extern const Gfx luigi_cap_on_eyes_left[];
extern const Gfx luigi_cap_on_eyes_up[];
extern const Gfx luigi_cap_on_eyes_down[];
extern const Gfx luigi_cap_on_eyes_dead[];
extern const Gfx luigi_metal_cap_on_shared_dl[];
extern const Gfx luigi_eyes_cap_off_dl[];
extern const Gfx luigi_mustache_cap_off_dl[];
extern const Gfx luigi_hair_sideburn_cap_off_dl[];
extern const Gfx luigi_face_part_cap_off_dl[];
extern const Gfx luigi_face_hair_cap_off_dl[];
extern const Gfx luigi_face_cap_off_dl[];
extern const Gfx luigi_cap_off_eyes_front[];
extern const Gfx luigi_cap_off_eyes_half_closed[];
extern const Gfx luigi_cap_off_eyes_closed[];
extern const Gfx luigi_cap_off_eyes_right[];
extern const Gfx luigi_cap_off_eyes_left[];
extern const Gfx luigi_cap_off_eyes_up[];
extern const Gfx luigi_cap_off_eyes_down[];
extern const Gfx luigi_cap_off_eyes_dead[];
extern const Gfx luigi_metal_cap_off_shared_dl[];
extern const Gfx luigi_medium_poly_butt_dl[];
extern const Gfx luigi_medium_poly_butt[];
extern const Gfx luigi_metal_medium_poly_butt[];
extern const Gfx luigi_medium_poly_left_arm_shared_dl[];
extern const Gfx luigi_medium_poly_left_arm[];
extern const Gfx luigi_medium_poly_left_forearm_shared_dl[];
extern const Gfx luigi_medium_poly_left_hand_closed_shared_dl[];
extern const Gfx luigi_medium_poly_left_hand_closed[];
extern const Gfx luigi_medium_poly_right_arm_shared_dl[];
extern const Gfx luigi_medium_poly_right_arm[];
extern const Gfx luigi_medium_poly_right_forearm_shared_dl[];
extern const Gfx luigi_medium_poly_right_hand_closed_dl[];
extern const Gfx luigi_medium_poly_right_hand_closed[];
extern const Gfx luigi_metal_medium_poly_right_hand_closed[];
extern const Gfx luigi_medium_poly_left_thigh_dl[];
extern const Gfx luigi_medium_poly_left_thigh[];
extern const Gfx luigi_metal_medium_poly_left_thigh[];
extern const Gfx luigi_medium_poly_left_leg_shared_dl[];
extern const Gfx luigi_medium_poly_left_foot_shared_dl[];
extern const Gfx luigi_medium_poly_left_foot[];
extern const Gfx luigi_medium_poly_right_thigh_shared_dl[];
extern const Gfx luigi_medium_poly_right_thigh[];
extern const Gfx luigi_medium_poly_right_leg_shared_dl[];
extern const Gfx luigi_medium_poly_right_foot_dl[];
extern const Gfx luigi_medium_poly_right_foot[];
extern const Gfx luigi_metal_medium_poly_right_foot[];
extern const Gfx luigi_medium_poly_yellow_button_dl[];
extern const Gfx luigi_medium_poly_pants_overalls_shared_dl[];
extern const Gfx luigi_medium_poly_tshirt_shared_dl[];
extern const Gfx luigi_medium_poly_torso_dl[];
extern const Gfx luigi_medium_poly_torso[];
extern const Gfx luigi_metal_medium_poly_torso[];
extern const Gfx luigi_low_poly_butt_dl[];
extern const Gfx luigi_low_poly_butt[];
extern const Gfx luigi_metal_low_poly_butt[];
extern const Gfx luigi_low_poly_left_arm_shared_dl[];
extern const Gfx luigi_low_poly_left_arm[];
extern const Gfx luigi_low_poly_left_forearm_shared_dl[];
extern const Gfx luigi_low_poly_left_hand_closed_shared_dl[];
extern const Gfx luigi_low_poly_left_hand_closed[];
extern const Gfx luigi_low_poly_right_arm_shared_dl[];
extern const Gfx luigi_low_poly_right_arm[];
extern const Gfx luigi_low_poly_right_forearm_shared_dl[];
extern const Gfx luigi_low_poly_right_hand_closed_dl[];
extern const Gfx luigi_low_poly_right_hand_closed[];
extern const Gfx luigi_metal_low_poly_right_hand_closed[];
extern const Gfx luigi_low_poly_left_thigh_dl[];
extern const Gfx luigi_low_poly_left_thigh[];
extern const Gfx luigi_metal_low_poly_left_thigh[];
extern const Gfx luigi_low_poly_left_leg_shared_dl[];
extern const Gfx luigi_low_poly_left_foot_shared_dl[];
extern const Gfx luigi_low_poly_left_foot[];
extern const Gfx luigi_low_poly_right_thigh_shared_dl[];
extern const Gfx luigi_low_poly_right_thigh[];
extern const Gfx luigi_low_poly_right_leg_shared_dl[];
extern const Gfx luigi_low_poly_right_foot_dl[];
extern const Gfx luigi_low_poly_right_foot[];
extern const Gfx luigi_metal_low_poly_right_foot[];
extern const Gfx luigi_low_poly_yellow_button_dl[];
extern const Gfx luigi_low_poly_pants_overalls_shared_dl[];
extern const Gfx luigi_low_poly_tshirt_shared_dl[];
extern const Gfx luigi_low_poly_torso_dl[];
extern const Gfx luigi_low_poly_torso[];
extern const Gfx luigi_metal_low_poly_torso[];
extern const Gfx luigi_low_poly_luigi_m_logo_dl[];
extern const Gfx luigi_low_poly_eyes_cap_on_dl[];
extern const Gfx luigi_low_poly_mustache_cap_on_dl[];
extern const Gfx luigi_low_poly_face_part_cap_on_dl[];
extern const Gfx luigi_low_poly_face_cap_dl[];
extern const Gfx luigi_low_poly_face_back_hair_cap_on_dl[];
extern const Gfx luigi_low_poly_face_cap_on_dl[];
extern const Gfx luigi_low_poly_cap_on_eyes_front[];
extern const Gfx luigi_low_poly_cap_on_eyes_half_closed[];
extern const Gfx luigi_low_poly_cap_on_eyes_closed[];
extern const Gfx luigi_low_poly_cap_on_eyes_right[];
extern const Gfx luigi_low_poly_cap_on_eyes_left[];
extern const Gfx luigi_low_poly_cap_on_eyes_up[];
extern const Gfx luigi_low_poly_cap_on_eyes_down[];
extern const Gfx luigi_low_poly_cap_on_eyes_dead[];
extern const Gfx luigi_metal_low_poly_cap_on[];
extern const Gfx luigi_low_poly_luigi_eyes_cap_off_dl[];
extern const Gfx luigi_low_poly_mustache_cap_off_dl[];
extern const Gfx luigi_low_poly_face_part_cap_off_dl[];
extern const Gfx luigi_low_poly_face_hair_cap_off_dl[];
extern const Gfx luigi_low_poly_face_cap_off_dl[];
extern const Gfx luigi_low_poly_cap_off_eyes_front[];
extern const Gfx luigi_low_poly_cap_off_eyes_half_closed[];
extern const Gfx luigi_low_poly_cap_off_eyes_closed[];
extern const Gfx luigi_low_poly_cap_off_eyes_right[];
extern const Gfx luigi_low_poly_cap_off_eyes_left[];
extern const Gfx luigi_low_poly_cap_off_eyes_up[];
extern const Gfx luigi_low_poly_cap_off_eyes_down[];
extern const Gfx luigi_low_poly_cap_off_eyes_dead[];
extern const Gfx luigi_metal_low_poly_cap_off[];
extern const Gfx luigi_left_hand_open_shared_dl[];
extern const Gfx luigi_left_hand_open[];
extern const Gfx luigi_right_hand_open_dl[];
extern const Gfx luigi_right_hand_open[];
extern const Gfx luigi_metal_right_hand_open[];
extern const Gfx luigi_right_hand_cap_m_logo_dl[];
extern const Gfx luigi_right_hand_cap_top_dl[];
extern const Gfx luigi_right_hand_cap_hand_position_dl[];
extern const Gfx luigi_right_hand_cap_bottom_dl[];
extern const Gfx luigi_right_hand_cap_dl[];
extern const Gfx luigi_right_hand_cap_wings_half_1_dl[];
extern const Gfx luigi_right_hand_cap_wings_half_2_dl[];
extern const Gfx luigi_right_hand_cap_wings_intial_dl[];
extern const Gfx luigi_right_hand_cap_wings_end_dl[];
extern const Gfx luigi_right_hand_cap[];
extern const Gfx luigi_right_hand_cap_wings[];
extern const Gfx luigi_metal_right_hand_cap_shared_dl[];
extern const Gfx luigi_metal_right_hand_cap_shared_dl_wings[];
extern const Gfx luigi_right_hand_peace_shared_dl[];
extern const Gfx luigi_right_hand_peace[];
extern const Gfx luigi_cap_unused_m_logo_dl[];
extern const Gfx luigi_cap_unused_base_top_dl[];
extern const Gfx luigi_cap_unused_base_bottom_dl[];
extern const Gfx luigi_cap_unused_base_dl[];
extern const Gfx luigi_wings_half_1_unused_dl[];
extern const Gfx luigi_wings_half_2_unused_dl[];
extern const Gfx luigi_cap_wings_unused_intial_dl[];
extern const Gfx luigi_cap_wings_unused_end_dl[];
extern const Gfx luigi_cap_unused_dl[];
extern const Gfx luigi_metal_cap_unused_dl[];
extern const Gfx luigi_cap_wings_unused[];
extern const Gfx luigi_metal_cap_wings_unused[];
extern const Gfx luigi_wings_half_1_dl[];
extern const Gfx luigi_wings_half_2_dl[];
extern const Gfx luigi_cap_wings[];
extern const Gfx luigi_cap_wings_transparent[];
extern const Gfx luigi_metal_cap_wings[];
extern const Gfx luigi_metal_cap_wings_transparent[];
extern Lights1 luigi_head_f3dlite_material_011_lights;
extern Lights1 luigi_head_f3dlite_material_012_lights;
extern Lights1 luigi_head_f3dlite_material_005_lights;
extern Lights1 luigi_head_f3dlite_material_lights;
extern Lights1 luigi_head_luigi_eyes_001_lights;
extern Lights1 luigi_head_f3dlite_material_003_lights;
extern Lights1 luigi_head_f3dlite_material_015_lights;
extern u64 luigi_head_luigi_logo_rgba16[];
extern u64 luigi_head_uigi_sideburn_rgba16_png_001_rgba16_rgba16[];
extern u64 luigi_head_mario_eyes_center_rgba16[];
extern u64 luigi_head_SM64_Luigi_Stache_ia8[];
extern Vtx luigi_head_skinned_001_mesh_vtx_0[15];
extern Gfx luigi_head_skinned_001_mesh_tri_0[];
extern Vtx luigi_head_skinned_001_mesh_vtx_1[22];
extern Gfx luigi_head_skinned_001_mesh_tri_1[];
extern Vtx luigi_head_skinned_001_mesh_vtx_2[92];
extern Gfx luigi_head_skinned_001_mesh_tri_2[];
extern Vtx luigi_head_skinned_001_mesh_vtx_3[230];
extern Gfx luigi_head_skinned_001_mesh_tri_3[];
extern Vtx luigi_head_skinned_001_mesh_vtx_4[33];
extern Gfx luigi_head_skinned_001_mesh_tri_4[];
extern Vtx luigi_head_skinned_001_mesh_vtx_5[47];
extern Gfx luigi_head_skinned_001_mesh_tri_5[];
extern Vtx luigi_head_skinned_001_mesh_vtx_6[128];
extern Gfx luigi_head_skinned_001_mesh_tri_6[];
extern Gfx mat_luigi_head_f3dlite_material_011[];
extern Gfx mat_luigi_head_f3dlite_material_012[];
extern Gfx mat_luigi_head_f3dlite_material_005[];
extern Gfx mat_luigi_head_f3dlite_material[];
extern Gfx mat_luigi_head_luigi_eyes_001[];
extern Gfx mat_luigi_head_f3dlite_material_003[];
extern Gfx mat_luigi_head_f3dlite_material_015[];

#include "boat/header.h"

#include "wario/geo_header.h"

#include "waluigi/geo_header.h"

#include "mario/geo_header.h"

// peach
extern const GeoLayout peach_geo_000098[];
extern const GeoLayout peach_geo_000254[];
extern const GeoLayout RCP_HmsEnemypeach_basic_skelton[];
extern const Gfx peach_seg5_dl_05005648[];
extern const Gfx peach_seg5_dl_05005750[];
extern const Gfx peach_seg5_dl_05005780[];
extern const Gfx peach_seg5_dl_050058B8[];
extern const Gfx peach_seg5_dl_050058E0[];
extern const Gfx peach_seg5_dl_05005C48[];
extern const Gfx peach_seg5_dl_05005CB0[];
extern const Gfx peach_seg5_dl_05005CE0[];
extern const Gfx peach_seg5_dl_05005D38[];
extern const Gfx peach_seg5_dl_05005D90[];
extern const Gfx peach_seg5_dl_05005DE8[];
extern const Gfx peach_seg5_dl_05005E40[];
extern const Gfx peach_seg5_dl_05005E98[];
extern const Gfx peach_seg5_dl_05005EF0[];
extern const Gfx peach_seg5_dl_05005F48[];
extern const Gfx peach_seg5_dl_05006058[];
extern const Gfx peach_seg5_dl_050060E0[];
extern const Gfx peach_seg5_dl_05006728[];
extern const Gfx peach_seg5_dl_05006798[];
extern const Gfx peach_seg5_dl_05006A18[];
extern const Gfx peach_seg5_dl_05006FA8[];
extern const Gfx peach_seg5_dl_05007230[];
extern const Gfx peach_seg5_us_dl_05007288[];
extern const Gfx peach_seg5_dl_05007810[];
extern const Gfx peach_seg5_dl_05007AB8[];
extern const Gfx peach_seg5_dl_05007CE8[];
extern const Gfx peach_seg5_dl_05007E58[];
extern const Gfx peach_seg5_dl_050080B8[];
extern const Gfx peach_seg5_dl_05008228[];
extern const Gfx peach_seg5_dl_05008428[];
extern const Gfx peach_seg5_dl_050084C0[];
extern const Gfx peach_seg5_dl_05008560[];
extern const Gfx peach_seg5_dl_050086C8[];
extern const Gfx peach_seg5_dl_050087A8[];
extern const Gfx peach_seg5_dl_05008978[];
extern const Gfx peach_seg5_dl_05008A10[];
extern const Gfx peach_seg5_dl_05008AB0[];
extern const Gfx peach_seg5_dl_05008C18[];
extern const Gfx peach_seg5_dl_05008CF8[];
extern const Gfx peach_seg5_dl_05008E38[];
extern const Gfx peach_seg5_dl_05008F20[];
extern const Gfx peach_seg5_dl_05009060[];
extern const Gfx peach_seg5_dl_05009148[];
extern const Gfx peach_seg5_dl_05009388[];
extern const Gfx peach_seg5_dl_05009500[];
extern const Gfx peach_seg5_dl_050097C0[];
extern const Gfx peach_seg5_dl_05009940[];
extern const Gfx peach_seg5_dl_05009E20[];
extern const Gfx peach_seg5_dl_0500A0A8[];
extern const Gfx peach_seg5_us_dl_0500A188[];
extern const struct Animation *const peach_seg5_anims_0501C41C[];

// bowser
extern const GeoLayout bowser_geo_0000D8[];
extern const GeoLayout bowser_geo_000424[];
extern const GeoLayout bowser_geo_000770[];
extern const GeoLayout bowser_shadow_geo[];
extern const GeoLayout bowser_geo[];
extern const GeoLayout bowser_geo_no_shadow[];
extern const Gfx bowser_seg6_dl_06039110[];
extern const Gfx bowser_seg6_dl_060391C8[];
extern const Gfx bowser_seg6_dl_06039260[];
extern const Gfx bowser_seg6_dl_060392E0[];
extern const Gfx bowser_seg6_dl_06039808[];
extern const Gfx bowser_seg6_dl_060398B0[];
extern const Gfx bowser_seg6_dl_06039958[];
extern const Gfx bowser_seg6_dl_060399D8[];
extern const Gfx bowser_seg6_dl_0603A210[];
extern const Gfx bowser_seg6_dl_0603A380[];
extern const Gfx bowser_seg6_dl_0603A4E8[];
extern const Gfx bowser_seg6_dl_0603AED8[];
extern const Gfx bowser_seg6_dl_0603B038[];
extern const Gfx bowser_seg6_dl_0603B208[];
extern const Gfx bowser_seg6_dl_0603B718[];
extern const Gfx bowser_seg6_dl_0603B8D0[];
extern const Gfx bowser_seg6_dl_0603B948[];
extern const Gfx bowser_seg6_dl_0603BDF8[];
extern const Gfx bowser_seg6_dl_0603BEA0[];
extern const Gfx bowser_seg6_dl_0603BF48[];
extern const Gfx bowser_seg6_dl_0603BFC8[];
extern const Gfx bowser_seg6_dl_0603C500[];
extern const Gfx bowser_seg6_dl_0603C5A8[];
extern const Gfx bowser_seg6_dl_0603C650[];
extern const Gfx bowser_seg6_dl_0603C6D0[];
extern const Gfx bowser_seg6_dl_0603CF28[];
extern const Gfx bowser_seg6_dl_0603D098[];
extern const Gfx bowser_seg6_dl_0603D200[];
extern const Gfx bowser_seg6_dl_0603DC70[];
extern const Gfx bowser_seg6_dl_0603DDD0[];
extern const Gfx bowser_seg6_dl_0603DFB0[];
extern const Gfx bowser_seg6_dl_0603E500[];
extern const Gfx bowser_seg6_dl_0603E6B8[];
extern const Gfx bowser_seg6_dl_0603FBA8[];
extern const Gfx bowser_seg6_dl_0603FC18[];
extern const Gfx bowser_seg6_dl_0603FD38[];
extern const Gfx bowser_seg6_dl_0603FDD0[];
extern const Gfx bowser_seg6_dl_0603FEA8[];
extern const Gfx bowser_seg6_dl_0603FFA8[];
extern const Gfx bowser_seg6_dl_06040180[];
extern const Gfx bowser_seg6_dl_060401F0[];
extern const Gfx bowser_seg6_dl_06040210[];
extern const Gfx bowser_seg6_dl_06040358[];
extern const Gfx bowser_seg6_dl_06041A28[];
extern const Gfx bowser_seg6_dl_06041BA0[];
extern const Gfx bowser_seg6_dl_06041E48[];
extern const Gfx bowser_seg6_dl_06041EA8[];
extern const Gfx bowser_seg6_dl_06041F50[];
extern const Gfx bowser_seg6_dl_06042098[];
extern const Gfx bowser_seg6_dl_060420F0[];
extern const Gfx bowser_seg6_dl_06042140[];
extern const Gfx bowser_seg6_dl_060421D8[];
extern const Gfx bowser_seg6_dl_06042220[];
extern const Gfx bowser_seg6_dl_06042278[];
extern const Gfx bowser_seg6_dl_06042328[];
extern const Gfx bowser_seg6_dl_06042348[];
extern const Gfx bowser_seg6_dl_060423A0[];
extern const Gfx bowser_seg6_dl_060423F8[];
extern const Gfx bowser_seg6_dl_06042450[];
extern const Gfx bowser_seg6_dl_060424A8[];
extern const Gfx bowser_seg6_dl_06042500[];
extern const Gfx bowser_seg6_dl_06042558[];
extern const Gfx bowser_seg6_dl_060425B0[];
extern const Gfx bowser_seg6_dl_06042608[];
extern const Gfx bowser_seg6_dl_06042EE0[];
extern const Gfx bowser_seg6_dl_060430E8[];
extern const Gfx bowser_seg6_dl_06043180[];
extern const Gfx bowser_seg6_dl_060431F0[];
extern const Gfx bowser_seg6_dl_06043548[];
extern const Gfx bowser_seg6_dl_06043648[];
extern const Gfx bowser_seg6_dl_06043698[];
extern const struct Animation *const bowser_seg6_anims_06057690[];
extern const s16 dBowserFlamesOrientationValues[];



#include "bowser/geo_header.h"

#include "yoshi/geo_header.h"

// bird
extern const GeoLayout birds_geo[];
extern const Gfx birds_seg5_dl_05000528[];
extern const Gfx birds_seg5_dl_05000598[];
extern const Gfx birds_seg5_dl_05000600[];
extern const Gfx birds_seg5_dl_05000670[];
extern const struct Animation *const birds_seg5_anims_050009E8[];

extern const GeoLayout yoshi_geo[];
extern const Gfx RCP_yoshi_base_data0[];
extern const Gfx RCP_yoshi_base_data1[];
extern const Gfx RCP_yoshi_base_data2[];
extern const Gfx RCP_yoshi_base_data3[];
extern const Gfx RCP_yoshi_base_data4[];
extern const Gfx RCP_yoshi_base_data5[];
extern const Gfx RCP_yoshi_base_data6[];
extern const Gfx RCP_yoshi_base_data7[];
extern const Gfx RCP_yoshi_base_data8[];
extern const Gfx RCP_yoshi_base_data9[];
extern const Gfx RCP_yoshi_base_data10[];
extern const Gfx RCP_yoshi_base_data11[];
extern const Gfx RCP_yoshi_base_data12[];
extern const Gfx RCP_yoshi_base_data13[];
extern const Gfx RCP_yoshi_base_data14[];
extern const Gfx RCP_yoshi_base_data15[];
extern const Gfx RCP_yoshi_base_data16[];
extern const struct Animation *const yoshi_seg5_anims_05024100[];


extern const GeoLayout metal_mario_geo[];


#endif
