extern const GeoLayout thwimp_geo[];
extern Lights1 thwimp_eyes2_lights;
extern Lights1 thwimp_eyesX_lights;
extern u8 thwimp_begula2_ci8[];
extern u8 thwimp_begula2_pal_rgba16[];
extern u8 thwimp_begula_rgba16[];
extern Vtx thwimp_000_displaylist_mesh_layer_1_vtx_0[58];
extern Gfx thwimp_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx thwimp_000_displaylist_mesh_layer_1_vtx_1[4];
extern Gfx thwimp_000_displaylist_mesh_layer_1_tri_1[];
extern Gfx mat_thwimp_eyes2[];
extern Gfx mat_revert_thwimp_eyes2[];
extern Gfx mat_thwimp_eyesX[];
extern Gfx thwimp_000_displaylist_mesh_layer_1[];
extern Gfx thwimp_material_revert_render_settings[];
