extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_005_lights;
extern Lights1 bob_dl_f3dlite_material_006_lights;
extern Lights1 bob_dl_f3dlite_material_007_lights;
extern u8 bob_dl_castle_grounds_textures_09800_rgba16_rgba16[];
extern u8 bob_dl_castle_grounds_textures_04000_rgba16_rgba16[];
extern u8 bob_dl_bob_textures_08000_rgba16_rgba16[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[20];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[21];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[13];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
