extern const GeoLayout sr_area_1_geo[];
extern const GeoLayout sr_area_1[];
extern const Collision sr_area_1_collision[];
extern const MacroObject sr_area_1_macro_objs[];
extern Lights1 sr_dl_f3dlite_material_003_layer1_area1_lights;
extern Lights1 sr_dl_SM64_pss_seg7_dl_0700A7C0_F3D_Mat_2_lights;
extern Lights1 sr_dl_f3dlite_material_002_layer1_area1_lights;
extern Lights1 sr_dl_f3dlite_material_005_layer1_area1_lights;
extern u8 sr_dl_wf_textures_04800_rgba16_rgba16[];
extern u8 sr_dl_ttm_textures_00000_rgba16_rgba16[];
extern u8 sr_dl_castle_grounds_textures_04000_rgba16_rgba16[];
extern u8 sr_dl__2_rgba16[];
extern u8 sr_dl__12_rgba16[];
extern Vtx sr_dl_Plane_mesh_layer_1_vtx_0[36];
extern Gfx sr_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx sr_dl_Plane_mesh_layer_1_vtx_1[134];
extern Gfx sr_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx sr_dl_Plane_mesh_layer_1_vtx_2[14];
extern Gfx sr_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx sr_dl_Plane_mesh_layer_1_vtx_3[214];
extern Gfx sr_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx sr_dl_Plane_mesh_layer_1_vtx_4[4];
extern Gfx sr_dl_Plane_mesh_layer_1_tri_4[];
extern Gfx mat_sr_dl_f3dlite_material_003_layer1_area1[];
extern Gfx mat_revert_sr_dl_f3dlite_material_003_layer1_area1[];
extern Gfx mat_sr_dl_SM64_pss_seg7_dl_0700A7C0_F3D_Mat_2[];
extern Gfx mat_sr_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_revert_sr_dl_f3dlite_material_002_layer1_area1[];
extern Gfx mat_sr_dl__2_001_f3d[];
extern Gfx mat_sr_dl_f3dlite_material_005_layer1_area1[];
extern Gfx mat_revert_sr_dl_f3dlite_material_005_layer1_area1[];
extern Gfx sr_dl_Plane_mesh_layer_1[];
extern Gfx sr_dl_material_revert_render_settings[];
