#include "src/game/envfx_snow.h"

const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_luigi_eyes_half_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_luigi_eyes_closed_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_left_002_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_right_002_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_up_002_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_down_002_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_luigi_eyes_dead_002_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_luigi_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt1),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt2),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt3),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt4),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt5),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt6),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt1_000_switch_001_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_luigi_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_luigi_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_luigi_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_luigi_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_luigi_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_luigi_eyes_half_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_luigi_eyes_closed_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_left_002_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_right_002_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_up_002_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_unused_luigi_eyes_down_002_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_luigi_eyes_dead_002_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt1),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt2),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt3),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt4),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt5),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt6),
			GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt1_000_switch_001_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_luigi_eyes_half_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_luigi_eyes_closed_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_left_002_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_right_002_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_up_002_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_down_002_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_luigi_eyes_dead_002_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 81, 0, 0, luigi_000_offset_torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_cap_off),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, -109, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_wing_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, 109, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_wing_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 55, -10, 65, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_hand_closed_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 56, -10, -65, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_hand_closed_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_open),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_peace),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_cap),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1_jump_luigi_luigi_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, 40, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 97, 0, 0, luigi_000_offset_left_leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 81, 0, 0, luigi_000_offset_left_foot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, -40, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 97, 0, 0, luigi_000_offset_right_leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_foot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_metal_004_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1_mat_override_metal_004_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1_mat_override_metal_004_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1_mat_override_metal_004_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_mat_override_metal_004_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_mat_override_metal_004_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_mat_override_metal_004_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1_mat_override_metal_004_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, luigi_000_offset_torso_mesh_layer_1_mat_override_metal_004_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_metal_004_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_cap_off),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, -109, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, luigi_000_displaylist_right_wing_mesh_layer_4_mat_override_metal_004_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, 109, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, luigi_000_displaylist_left_wing_mesh_layer_4_mat_override_metal_004_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 55, -10, 65, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1_mat_override_metal_004_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1_mat_override_metal_004_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_left_hand_closed_mesh_layer_1_mat_override_metal_004_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 56, -10, -65, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1_mat_override_metal_004_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1_mat_override_metal_004_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_hand_closed_mesh_layer_1_mat_override_metal_004_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_open),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_peace),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_cap),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2_jump_luigi_luigi_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, 40, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1_mat_override_metal_004_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 97, 0, 0, luigi_000_offset_left_leg_mesh_layer_1_mat_override_metal_004_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, luigi_000_offset_left_foot_mesh_layer_1_mat_override_metal_004_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, -40, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1_mat_override_metal_004_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 97, 0, 0, luigi_000_offset_right_leg_mesh_layer_1_mat_override_metal_004_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_004_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_switch_000_displaylist_cap_off_mesh_layer_1_mat_override_metal_004_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_000_switch_option_000_offset_left_hand_open_mesh_layer_1_mat_override_metal_004_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_open_mesh_layer_1_mat_override_metal_004_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_peace_mesh_layer_1_mat_override_metal_004_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_cap_mesh_layer_1_mat_override_metal_004_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 71, 0, 0, luigi_001_switch_option_000_offset_right_hand_wing_cap_mesh_layer_1_mat_override_metal_004_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_001_switch_option_000_displaylist_right_hand_cap_wings_mesh_layer_4_mat_override_metal_004_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1_mat_override_metal_004_0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 81, 0, 0, luigi_000_offset_torso_mesh_layer_1_mat_override_metal_004_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_metal_004_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_cap_off),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, -109, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_wing_mesh_layer_4_mat_override_metal_004_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, 109, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_wing_mesh_layer_4_mat_override_metal_004_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 55, -10, 65, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1_mat_override_metal_004_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1_mat_override_metal_004_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_left_hand_closed_mesh_layer_1_mat_override_metal_004_0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 56, -10, -65, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1_mat_override_metal_004_0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1_mat_override_metal_004_0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_hand_closed_mesh_layer_1_mat_override_metal_004_0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_open),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_peace),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_cap),
										GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3_jump_luigi_luigi_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, 40, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1_mat_override_metal_004_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 97, 0, 0, luigi_000_offset_left_leg_mesh_layer_1_mat_override_metal_004_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 81, 0, 0, luigi_000_offset_left_foot_mesh_layer_1_mat_override_metal_004_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, -40, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1_mat_override_metal_004_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 97, 0, 0, luigi_000_offset_right_leg_mesh_layer_1_mat_override_metal_004_0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, luigi_000_displaylist_right_foot_mesh_layer_1_mat_override_metal_004_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_luigi_eyes_half_002_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_luigi_eyes_closed_002_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_left_002_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_right_002_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_up_002_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_unused_luigi_eyes_down_002_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1_mat_override_luigi_eyes_dead_002_7),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout luigi_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_set_player_luigi),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 22, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, luigi_000_offset_torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 90, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_cap_on_mesh_layer_1),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
																	GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, luigi_luigi_cap_off),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, -109, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, luigi_000_displaylist_right_wing_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 140, -50, 109, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, luigi_000_displaylist_left_wing_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 55, -10, 65, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_upperarm_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_left_forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_left_hand_closed_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, luigi_luigi_left_hand_open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 56, -10, -65, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_upperarm_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 0, luigi_000_offset_right_forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 71, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_hand_closed_mesh_layer_1),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, luigi_luigi_right_hand_open),
																GEO_BRANCH(1, luigi_luigi_right_hand_peace),
																GEO_BRANCH(1, luigi_luigi_right_hand_cap),
																GEO_BRANCH(1, luigi_luigi_right_hand_wing_cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, 40, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_left_thigh_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 97, 0, 0, luigi_000_offset_left_leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, luigi_000_offset_left_foot_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 15, -9, -40, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, luigi_000_offset_right_thigh_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 97, 0, 0, luigi_000_offset_right_leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 81, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, luigi_000_displaylist_right_foot_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, luigi_002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
